language: vi

reviews:
  profile: senior-dev

  auto_review:
    enabled: true
    drafts: false
    min_changed_lines: 10

  rules:
    - security
    - performance
    - readability
    - best-practices
    - testing

  focus:
    frontend:
      - "Remove redundant JSX / template elements"
      - "Avoid unnecessary wrappers (div/span hell)"
      - "Follow framework conventions strictly"
      - "Split large components into smaller reusable ones"
      - "Avoid inline logic inside JSX/templates"
      - "Avoid duplicated UI logic"
    backend:

  ignore:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "coverage/**"
    - "*.lock"
    - "**/*.min.js"
    - "**/*.min.css"
    - "**/*.map"

  comment_settings:
    max_comments: 25
    verbosity: concise
