language: en

reviews:
  profile: senior-dev

  auto_review:
    enabled: true
    drafts: false

  rules:
    - security
    - performance
    - readability
    - best-practices
    - testing

  ignore:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "coverage/**"
    - "*.lock"
    - "**/*.min.js"
    - "**/*.min.css"
    - "**/*.map"

  comment_settings:
    max_comments: 25
    verbosity: concise
